import { type ImageSourcePropType } from "react-native";

// Bundled Live TV channel logos, keyed by LiveChannel id. RN/expo-image can't render
// the SVGs the web ships, so these are PNG rasters: the first block are ported brand
// logos; the rest are the web brand-lockup thumbs (assets/images/live-thumbs/<id>.svg)
// rasterized to PNG with the baked-in LIVE pill stripped — the tile overlays its own
// LIVE badge. Channels without an entry fall back to a logo-less tile.
export const LIVE_LOGOS: Record<string, ImageSourcePropType> = {
  "bloomberg-tv-us": require("../../assets/images/live-thumbs/bloomberg-tv-us.png"),
  "bbc-news": require("../../assets/images/live-thumbs/bbc-news.jpg"),
  "sky-news": require("../../assets/images/live-thumbs/sky-news.png"),
  "bbc-us": require("../../assets/images/live-thumbs/bbc-us.png"),
  cnn: require("../../assets/images/live-thumbs/cnn.png"),
  "fox-news": require("../../assets/images/live-thumbs/fox-news.png"),
  "espn-2-us": require("../../assets/images/live-thumbs/espn-2-us.png"),
  hbo: require("../../assets/images/live-thumbs/hbo.png"),
  "discovery-channel": require("../../assets/images/live-thumbs/discovery-channel.png"),
  "national-geographic": require("../../assets/images/live-thumbs/national-geographic.png"),
  ert1: require("../../assets/images/live-thumbs/ert1.jpg"),
  "mega-news": require("../../assets/images/live-thumbs/mega-news.jpg"),
  ant1: require("../../assets/images/live-thumbs/ant1.png"),
  "alpha-tv": require("../../assets/images/live-thumbs/alpha-tv.png"),
  "top-news": require("../../assets/images/live-thumbs/top-news.jpg"),
  "novasports-1": require("../../assets/images/live-thumbs/novasports-1.png"),
  "novasports-2": require("../../assets/images/live-thumbs/novasports-2.png"),
  "novasports-3": require("../../assets/images/live-thumbs/novasports-3.png"),
  "novasports-4": require("../../assets/images/live-thumbs/novasports-4.png"),
  "novasports-5": require("../../assets/images/live-thumbs/novasports-5.png"),
  "novasports-6": require("../../assets/images/live-thumbs/novasports-6.png"),
  // Rasterized brand-lockup thumbs (UK / France / Greece / Portugal / Netherlands sports + ITV):
  "sky-sports-main-event": require("../../assets/images/live-thumbs/sky-sports-main-event.png"),
  "sky-sports-premier-league": require("../../assets/images/live-thumbs/sky-sports-premier-league.png"),
  "sky-sports-football": require("../../assets/images/live-thumbs/sky-sports-football.png"),
  "sky-sports-action": require("../../assets/images/live-thumbs/sky-sports-action.png"),
  "sky-sports-f1": require("../../assets/images/live-thumbs/sky-sports-f1.png"),
  "sky-sports-golf": require("../../assets/images/live-thumbs/sky-sports-golf.png"),
  "sky-sports-tennis": require("../../assets/images/live-thumbs/sky-sports-tennis.png"),
  "sky-sports-mix": require("../../assets/images/live-thumbs/sky-sports-mix.png"),
  "tnt-sports-1": require("../../assets/images/live-thumbs/tnt-sports-1.png"),
  "tnt-sports-2": require("../../assets/images/live-thumbs/tnt-sports-2.png"),
  "tnt-sports-3": require("../../assets/images/live-thumbs/tnt-sports-3.png"),
  "tnt-sports-4": require("../../assets/images/live-thumbs/tnt-sports-4.png"),
  "premier-sports-1": require("../../assets/images/live-thumbs/premier-sports-1.png"),
  "premier-sports-2": require("../../assets/images/live-thumbs/premier-sports-2.png"),
  "eurosport-1": require("../../assets/images/live-thumbs/eurosport-1.png"),
  "eurosport-2": require("../../assets/images/live-thumbs/eurosport-2.png"),
  "viaplay-sports-la-liga": require("../../assets/images/live-thumbs/viaplay-sports-la-liga.png"),
  "bein-sports-1-uk": require("../../assets/images/live-thumbs/bein-sports-1-uk.png"),
  "itv-1": require("../../assets/images/live-thumbs/itv-1.png"),
  "itv-2": require("../../assets/images/live-thumbs/itv-2.png"),
  "itv-3": require("../../assets/images/live-thumbs/itv-3.png"),
  "itv-4": require("../../assets/images/live-thumbs/itv-4.png"),
  "lfc-tv": require("../../assets/images/live-thumbs/lfc-tv.png"),
  "mutv": require("../../assets/images/live-thumbs/mutv.png"),
  "bein-sports-1": require("../../assets/images/live-thumbs/bein-sports-1.png"),
  "bein-sports-2": require("../../assets/images/live-thumbs/bein-sports-2.png"),
  "bein-sports-3": require("../../assets/images/live-thumbs/bein-sports-3.png"),
  "bein-sports-max-4": require("../../assets/images/live-thumbs/bein-sports-max-4.png"),
  "bein-sports-max-5": require("../../assets/images/live-thumbs/bein-sports-max-5.png"),
  "bein-sports-max-6": require("../../assets/images/live-thumbs/bein-sports-max-6.png"),
  "bein-sports-max-7": require("../../assets/images/live-thumbs/bein-sports-max-7.png"),
  "bein-sports-max-8": require("../../assets/images/live-thumbs/bein-sports-max-8.png"),
  "bein-sports-max-9": require("../../assets/images/live-thumbs/bein-sports-max-9.png"),
  "canal-plus-sport": require("../../assets/images/live-thumbs/canal-plus-sport.png"),
  "canal-plus-sport-360": require("../../assets/images/live-thumbs/canal-plus-sport-360.png"),
  "canal-plus-foot": require("../../assets/images/live-thumbs/canal-plus-foot.png"),
  "rmc-sport-1": require("../../assets/images/live-thumbs/rmc-sport-1.png"),
  "rmc-sport-2": require("../../assets/images/live-thumbs/rmc-sport-2.png"),
  "lequipe": require("../../assets/images/live-thumbs/lequipe.png"),
  "cosmote-sport-1": require("../../assets/images/live-thumbs/cosmote-sport-1.png"),
  "cosmote-sport-2": require("../../assets/images/live-thumbs/cosmote-sport-2.png"),
  "cosmote-sport-3": require("../../assets/images/live-thumbs/cosmote-sport-3.png"),
  "cosmote-sport-4": require("../../assets/images/live-thumbs/cosmote-sport-4.png"),
  "cosmote-sport-5": require("../../assets/images/live-thumbs/cosmote-sport-5.png"),
  "cosmote-sport-6": require("../../assets/images/live-thumbs/cosmote-sport-6.png"),
  "cosmote-sport-7": require("../../assets/images/live-thumbs/cosmote-sport-7.png"),
  "cosmote-sport-8": require("../../assets/images/live-thumbs/cosmote-sport-8.png"),
  "cosmote-sport-9": require("../../assets/images/live-thumbs/cosmote-sport-9.png"),
  "sport-tv-1": require("../../assets/images/live-thumbs/sport-tv-1.png"),
  "sport-tv-2": require("../../assets/images/live-thumbs/sport-tv-2.png"),
  "sport-tv-3": require("../../assets/images/live-thumbs/sport-tv-3.png"),
  "sport-tv-4": require("../../assets/images/live-thumbs/sport-tv-4.png"),
  "sport-tv-5": require("../../assets/images/live-thumbs/sport-tv-5.png"),
  "sport-tv-6": require("../../assets/images/live-thumbs/sport-tv-6.png"),
  "sport-tv-7": require("../../assets/images/live-thumbs/sport-tv-7.png"),
  "benfica-tv": require("../../assets/images/live-thumbs/benfica-tv.png"),
  "canal-11": require("../../assets/images/live-thumbs/canal-11.png"),
  "espn-1-nl": require("../../assets/images/live-thumbs/espn-1-nl.png"),
  "espn-2-nl": require("../../assets/images/live-thumbs/espn-2-nl.png"),
  "espn-3-nl": require("../../assets/images/live-thumbs/espn-3-nl.png"),
  "espn-4-nl": require("../../assets/images/live-thumbs/espn-4-nl.png"),
  "ziggo-sport": require("../../assets/images/live-thumbs/ziggo-sport.png"),
  "ziggo-sport-2": require("../../assets/images/live-thumbs/ziggo-sport-2.png"),
  "ziggo-sport-3": require("../../assets/images/live-thumbs/ziggo-sport-3.png"),
  "ziggo-sport-4": require("../../assets/images/live-thumbs/ziggo-sport-4.png"),
  "ziggo-sport-5": require("../../assets/images/live-thumbs/ziggo-sport-5.png"),
  "ziggo-sport-6": require("../../assets/images/live-thumbs/ziggo-sport-6.png"),
};
